### ISSUE TITLE
Simpler branch scheme

### ISSUE THREAD

**Issue by samoht** [ocaml/opam-publish#23]
- The current branch scheme is a bit confusing (ie. using local master and remote `opam-publish/<package.version>`. It would be simpler to have the same branch name on both repositories (and make it `<package.version>` no need for the prefix)
- The current repository name is also not very usual. In my opinion, it would be better to have:
  - the user repository should be named `origin`
  - the main repository should be named `upstream`

When all of this is set, it then becomes easier to manually modify `~/.opam/plugins/opam-publish/default`, which happens quite often in practice.

**Comment by AltGr** [comment]
Fair enough, doesn't seem like a difficult change (but might break ongoing publishings when you upgrade!). My idea when using `opam-publish/pkg.version` was that you may already have a personal clone of the repository, and I didn't want to interfere with the normal user namespace (this way if you go to `https://github.com/me/opam-repository` you don't have to wonder where all these branches come from. But that may be unneeded and too heavy...

**Comment by rjbou** [comment]
Seems deprecated with current versions. Thanks!
