### ISSUE TITLE
Allow to specify an opam file on the command line

### ISSUE THREAD

**Issue by samoht** [ocaml/opam-publish#24]
or check for `package.opam` in the current directory. That's pretty useful for multi-package repositories (such as `mirage/mirage-platform`)

**Comment by c-cube** [comment]
This would be useful to me as well. Maybe an option to specify a sub-path in the archive (instead of `package/opam`) would work, too.

**Comment by rgrinberg** [comment]
Would be nice to have a fix for this pre 2.0

**Comment by AltGr** [comment]
`opam build` basically provides handling for opam files from CWD, among other things. But providing a more generally available option (`--cwd`) that would take these files, add them to the universe, and proceed like the packages had been specified on the command-line would indeed be of wider use. E.g. `opam install --cwd` would be more obvious within the current workflows than `opam build --no-autoinit`.

Note that a few commands now deal with opam files, among them `opam lint`, and that `opam pin <dir>` will handle all package definitions found in `.` and is how you would handle this in general.

**Comment by rjbou** [comment]
Handled by current version. Thanks!
