### ISSUE TITLE
`opam-publish prepare` URL contents silently overriden by current pin

### ISSUE THREAD

**Issue by mcclure** [ocaml/opam-publish#26]
I follow these steps:

I create a directory `opam-publish-test-pinned`. In it I place a file `opam` containing:

```
opam-version: "1.2"
license: "Sasquatch"
maintainer: "Sasquatch2"
author: "Sasquatch3"
homepage: "http://example.com/Sasquatch4"
bug-reports: "http://example.com/Sasquatch5"
dev-repo: "git+ssh://git@github.com/mcclure/ppx_publish_test.git"
```

I run:

```
opam pin add opam-publish-test /Users/mcc/work/h/opam-garbage/opam-publish-test-pinned
```

This package is now pinned.

I create a new directory, `opam-publish-test`. In it I place a file `opam` containing:

```
opam-version: "1.2"
license: "crunch"
maintainer: "crunch2"
author: "crunch3"
homepage: "http://example.com/crunch4"
bug-reports: "http://example.com/crunch5"
dev-repo: "git+ssh://git@github.com/mcclure/ppx_publish_test.git"
```

I create a zipfile `opam-publish-test-archive.zip` of the `opam-publish-test` directory.

I enter a new, empty directory. I run:

```
opam-publish prepare opam-publish-test.1.0 /Users/mcc/work/h/opam-garbage/opam-publish-test/opam-publish-test-archive.zip
```

`opam-publish prepare` does the thing it does. There is now a directory `opam-publish-test.1.0` in the current directory. I run `cat opam-publish-test.1.0/opam`.

Expected behavior: 

I expect that the generated opam file will contain the word "crunch" over and over. This is what I expect based on both intuition from the command I just ran, and on what it says in `opam-publish --help` ("Provided a remote archive URL, gathers metadata for an OPAM package suitable for editing and submitting to an OPAM repo.")

Observed behavior: the generated opam file contains

```
opam-version: "1.2"
maintainer: "Sasquatch2"
authors: "Sasquatch3"
homepage: "http://example.com/Sasquatch4"
bug-reports: "http://example.com/Sasquatch5"
license: "Sasquatch"
dev-repo: "git+ssh://git@github.com/mcclure/ppx_publish_test.git"
```

So it is somehow picking all the content out of the currently pinned "opam-publish-test" package, not the file I directed it at. AltGr on #ocaml freenode looked at the code and highlighted [this line of code](https://github.com/OCamlPro/opam-publish/blob/master/src/opam_publish.ml#L588), which I believe they said says "the archive" has low priority. However, no documentation I can find suggests any data source other than the provided archive URL will be queried at all, much less that some of those data sources are higher priority than the archive URL.

I think you should do one or more of the following:
- Make the generated opam file grab keys from the provided URL only, to match the current documentation
- If the current behavior stays, document it in opam-publish --help and the README.
- If the final behavior is that more than one data source is queried (especially if some of them are implicit), the opam-publish prepare should print out the exact data sources it used to prepare the template along with the other messages it currently prints, so that the user is not surprised.

Overall the current behavior is surprising, it almost caused me to submit an opam file with incorrect information.

**Comment by mcclure** [comment]
Sorry, I should have mentioned: This is with opam-publish 0.2.1, installed via opam on OS X.

**Comment by AltGr** [comment]
`opam-publish` does gather from a number of sources (anything that might be available, really). I tried to make the order of priority as sensible as possible, but that's not easy: it may be tweaked or better documented.
From https://github.com/OCamlPro/opam-publish/blob/429a4d6946815d4348ac24824d50e9b530716aec/src/opam_publish.ml#L592-L595 , the current priority is (highest first):
- the data from the pin (supposing you're testing the current version with 'opam pin' as you go, it should be the latest)
- the data from a previous run of `opam publish prepare`
- the data from a pre-existing PR by the user for this package version
- the data from the local OPAM repository clone
- last, data from the archive
- for the description only, data from another version of the same package in the repo

**Comment by rjbou** [comment]
Seems a 0.3.5 issue, closing.
