### ISSUE TITLE
Remove name and version from opam files before publication?

### ISSUE THREAD

**Issue by dsheets** [ocaml/opam-publish#28]
`opam` package files in directory repositories get their name and version from the directory structure rather than the metadata file. `opam` files in package development repositories use these fields to make pinning easier. There is a gestating policy to have `name` and `version` removed in `opam` files submitted to ocaml/opam-repository. It would be nice to have these fields automatically removed by `opam publish`.

**Comment by dbuenzli** [comment]
This idea doesn't seem to take into account the signing stuff (@hannesm). Rather I would argue that tooling like opam-publish should automatically add these so that the versions we have in the repositories don't get out of sync.

**Comment by hannesm** [comment]
I think while people shouldn't be bothered with manually inserting version numbers and names, opam files should actually contain these (by using some automation, such as opam publish). this would also simplify opam to only have to take a single metadata file into account, and not trying to inferring implicit information from path structures...

**Comment by dra27** [comment]
Cross-referencing https://github.com/ocaml/opam/issues/2320#issuecomment-154657852

**Comment by grayswandyr** [comment]
Hi

regarding [this discussion](https://github.com/dbuenzli/topkg/issues/125#issuecomment-360201393), it seems that `opam lint` and `opam publish` do not handle the presence (or not) of these fields in the same way. I don't know how and where it should be addressed, but this is very misleading for beginners.
Thank you.

**Comment by rjbou** [comment]
Fixed in current version. Thanks!

@grayswandyr `opam lint` do some checks, but not all from what is required by opam repository. Linting is more here to ensure that your opam file is well formed, than make it opam repository compatible. cf. #101
