### ISSUE TITLE
Allow findlib files

### ISSUE THREAD

**Issue by Chris00** [ocaml/opam-publish#32]
I know that the `findlib` file is still experimental but I think that `opam-publish` should _not_ fail when it is present.

**Comment by dbuenzli** [comment]
I still don't remember where these `findlib` files came from but I think that these are one more crap file in the opam system. Why not simply have a `x-findlib` field in opam files ?

**Comment by Chris00** [comment]
A `x-findlib` section would be fine with me. My point is that, whatever solution is adopted, it needs to be understood by `opam-publish`.

**Comment by dbuenzli** [comment]
See https://github.com/ocaml/opam/issues/2254
