### ISSUE TITLE
Please provide alternatives to typing github password in console

### ISSUE THREAD

**Issue by emillon** [ocaml/opam-publish#35]
Hi,

First, thanks for this tool, I believe that it helps a lot in contributing to `opam-repository` and is in part responsible for opam's success.

However I would like to raise a concern related to the of the security of the initial login: in order to setup the authorization token, `opam-publish` prompts for the user's github password on its command line.

While I understand that opam-publish is open source and I can examine it to make sure that this password is only passed to github's API, this is not satisfying. The whole purpose of using a oauth token is that as a user, I should only type my github password in a browser, under a github URL.

[Github supports](https://help.github.com/articles/creating-an-access-token-for-command-line-use/) manually creating a token so that it can be inserted into an application. It would be indeed great to have a `opam-publish setup --token 0123456789abcdef` command, or to have an option so that the initial `opam-publish` command would prompt for a manually generated access token instead of the master password.

What do you think?

Thanks!

**Comment by leowzukw** [comment]
:+1:

**Comment by dbuenzli** [comment]
> What do you think?

I think this should not be done through a command line option but rather on stdin (as you suggest) or through an environment variable to make it less peekable by other users. 

If you need a workaround directly writing the token in the content of the path:
 
`$(opam config var root)/plugins/opam-publish/$(GITHUB_USER).token`

should do it.

**Comment by emillon** [comment]
OK, I managed to do this by hand! Here's the full process:

  - go to <https://github.com/settings/tokens/new>
  - create a token with the `public_repo` scope
  - copy it to `~/.opam/plugins/opam-publish/$GH_USER.token`. Important: there must not be a trailing newline in this file, so either use `echo -n` or remove the newline inserted by your editor (I used `perl -pi -e 'chomp if eof' ~/.opam/plugins/opam-publish/$GH_USER.token`)
  - when submitting your first package, you need to pass `-n $GH_USER` to `opam publish` so that it knows how to initialize its underlying git repository

I identified a couple quirks in the process:

  - `opam-publish` creates a token with `repo` scope by default. This means that it has access to public and private repositories, which seems like a dangerous default to me. I believe that since it targets `opam-repository` by default, the scope should be `public_repo` (with a switch in case you want to generate a token for a private repository)
  - the function that reads the token does not ignore whitespace. Since tokens are ASCII and meant to be pasted in config files, it should at least accept a trailing newline.
  - if the token cannot be read, not only the message is inexact ("Existing token is no longer valid.") but it also immediately deletes the token file! Which is unfortunate if it actually contained valuable information (such as a token without a trailing newline :smiley:)

I'd be happy to provide a patch for each of these issues if you're interested.

:sparkles: Thanks! :sparkles:

**Comment by emillon** [comment]
Not sure when this was fixed, but now `dune-release publish` just asked a token and managed this by hand, so it seems that it was fixed. Thanks!
