### ISSUE TITLE
url file location field should be archive in preference to http

### ISSUE THREAD

**Issue by dsheets** [ocaml/opam-publish#36]
Currently, opam publish produces `url` files with an `http:` location field. While this works, it is confusing (in the `https` case) and redundant with the URI scheme already present in its value.

**Comment by AltGr** [comment]
Indeed. The [dev version](https://github.com/ocaml/opam/blob/7bc3a591acc2c2323d3f2c26c235f113b83525c9/src/format/opamFile.ml#L1107-L1108) of opam deprecates all variants of the field but `src:`.

**Comment by AltGr** [comment]
(this is also in the corresponding [doc](https://github.com/ocaml/opam/blob/master/doc/pages/Manual.md#url))

**Comment by rjbou** [comment]
Seems fixed
