### ISSUE TITLE
Submit transaction

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/opam-publish#38]
This should be designed with #29 in mind. Sometimes you'd like to submit a set of packages in a single submission otherwise the repo may be in an inconsistant state at some commits. 

Something like 

```
opam publish submit --add PKG1
opam publish submit --add PKG2
opam publish submit --commit
```

**Comment by tekknolagi** [comment]
@dbuenzli do you envision this maintaining state somehow in a file? Why not just prepare/add all at once?

**Comment by dbuenzli** [comment]
> Why not just prepare/add all at once?

I think it will make things painful if you need to correct and resubmit, also *all at once* will be difficult to solve with #29.

**Comment by tekknolagi** [comment]
Where do you propose the state is kept -- a file? Stored where?

**Comment by dbuenzli** [comment]
> Where do you propose the state is kept

I'm not proposing an implementation I'm proposing an UI.

**Comment by dbuenzli** [comment]
But given what I wrote in #29 I think a file format should be defined that allows to describe changes to an opam repo (constraints updates + paths to new packages to add) and that the tool should then consume these files to update the repo in a single commit. No state needs to be kept by `opam-submit` itself.

**Comment by tekknolagi** [comment]
> I think it will make things painful if you need to correct and resubmit

@dbuenzli wouldn't you have ordinarily done your checks and corrections after the preparation stage? So this is just uploading a PR?

**Comment by dbuenzli** [comment]
> @dbuenzli wouldn't you have ordinarily done your checks and corrections after the preparation stage? So this is just uploading a PR?

Maintainers and bots may think badly about our PR.

**Comment by tekknolagi** [comment]
So these are opam-publish transactions on PRs that already exist?

**Comment by samoht** [comment]
btw, I have started to use that [workaround](https://github.com/mirage/irmin/blob/master/Makefile#L11-L24) in mirage packages to allow multi-packages submit.

**Comment by rjbou** [comment]
As current version allows to give several packages, seems that it is resolved. Feel free to reopen if needed.
Thanks!
