### ISSUE TITLE
Port to opam v2.0 libs

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/opam-publish#52]
I tried to give it a shot but the APIs seem to have diverged too much for me to this efficiently.

**Comment by AltGr** [comment]
Thanks for trying! I'll do it as soon as I have a minute

**Comment by dbuenzli** [comment]
> as I have a minute

A minute ? Did I try not hard enough ?

**Comment by AltGr** [comment]
Hmm, not a minute-long minute, more a figure-of-speach minute :)
