### ISSUE TITLE
opam-publish fails with OpamSystem.Process_error

### ISSUE THREAD

**Issue by lebotlan** [ocaml/opam-publish#55]
opam-publish 0.3.4 fails with Process_error and is not helpful (gives no useful information).

I am probably to blame for the Process_error, but opam-publish should give more detailed information.

How to reproduce:
 git clone https://github.com/lebotlan/ocaml-cryptodbm.git
 cd ocaml-cryptodbm/
 opam-publish prepare cryptodbm-v0.82.0 https://github.com/lebotlan/ocaml-cryptodbm/archive/cryptodbm-v0.82.0.tar.gz

(By the way, I am not sure this is the canonical way to publish... any advice will be appreciated).

The above command gives :
[cryptodbm-v0.82.0.tar.gz] https://github.com/lebotlan/ocaml-cryptodbm/archive/cryptodbm-v0.82.0.tar.gz downloaded
OpamSystem.Process_error(_)
Backtrace:
  Raised at file "map.ml", line 122, characters 10-25
  Called from file "src0/sexp_conv.ml", line 149, characters 10-37

Strangely enough, it succeeded this morning with another package (exenum), but seems to fail now.

**Comment by AltGr** [comment]
> git clone https://github.com/lebotlan/ocaml-cryptodbm.git
> cd ocaml-cryptodbm/
> opam-publish prepare cryptodbm-v0.82.0 https://github.com/lebotlan/ocaml-cryptodbm/archive/cryptodbm-v0.82.0.tar.gz
>
> (By the way, I am not sure this is the canonical way to publish... any advice will be appreciated).

We are re-designing the interface to be more obvious. but the current one relies on the archive, so the initial clone is not needed: you can do just the last step:

     opam-publish prepare cryptodbm-v0.82.0 $URL
    ~~ edit cryptodbm-v0.82.0/opam (assuming the first step was successful) ~~
    opam-publish submit cryptodbm-v0.82.0

Also, opam splits between package name and version at `.`, so the above declares a package named `cryptodbm-v0`, version `82.0`. Unlikely to be what you want... The latest dev version (I'll make a new release soon) gives me the more helpful:

    [ERROR] There are <pkg>.opam files/directories but no cryptodbm-v0.opam. I can't decide which opam file to use.

Indeed you get better results with `opam-publish prepare cryptodbm.0.82.0 $URL`

**Comment by lebotlan** [comment]
Thanks for replying.
Actually, with opam-publish 0.3.4, it still fails:

opam-publish prepare cryptodbm.0.82.0 "https://..."
OpamSystem.Process_error(_)
Backtrace:
  Raised at file "map.ml", line 122, characters 10-25
  Called from file "src0/sexp_conv.ml", line 149, characters 10-37


I can try the dev version, but it requires to install a couple of opam-blabla 2.0.0~beta packages. How safe is it to install these, whereas my current opam installation is 1.2.2 ?

(Also, I am not in a hurry, so I can as well wait for a release.)

**Comment by AltGr** [comment]
I'll release shortly, so you shouldn't need to bother with the dev version.

> I can try the dev version, but it requires to install a couple of opam-blabla 2.0.0~beta packages. How safe is it to install these, whereas my current opam installation is 1.2.2 ?

These are safe (they won't interact with the existing opam installation) — **but** using that version of opam-publish, you will get validation of package definitions according to the 2.0 spec, which is not desirable at this stage. I'll fix the `dev-repo:` field to point to the correct branch to avoid this.

**Comment by lebotlan** [comment]
Hi,

I have a new problem now, with opam-publish v0.3.5. I don't understand what "git fetch origin user" tries to do.

opam-publish prepare cryptodbm.0.82.0 https://github.com/lebotlan/ocaml-cryptodbm/archive/cryptodbm-v0.82.0.tar.gz

[cryptodbm-v0.82.0.tar.gz] https://github.com/lebotlan/ocaml-cryptodbm/archive/cryptodbm-v0.82.0.tar.gz downloaded
# opam-version 1.3.1
# os           linux
# command      git fetch --multiple origin user
# path         /home/opam/.opam/plugins/opam-publish/repos/default
# exit-code    1
# env-file     /tmp/opam-xxx-21020/log-21020-05296d.env
# stdout-file  /tmp/opam-xxx-21020/log-21020-05296d.out
# stderr-file  /tmp/opam-xxx-21020/log-21020-05296d.err
### stdout ###
# Récupération de origin
# Récupération de user
### stderr ###
# ERROR: Repository not found.
# fatal: Could not read from remote repository.
# 
# Please make sure you have the correct access rights
# and the repository exists.
# error: Impossible de récupérer user

**Comment by lebotlan** [comment]
Still having the same problem with 'git fetch origin user' ..any hint ?

**Comment by AltGr** [comment]
Sorry for the long delay...
`opam-publish` works by filing a Github PR to the opam-repository, and for that handles a local clone in `~/.opam/plugins/opam-publish/repos/default`. I guess that, in your case, something got wrong in that directory, and the tool no longer manages to handle it. I would suggest just removing the directory, and let it be recreated by opam on the next `submit`. Alternatively, try `opam-publish repo remove default`, which should be equivalent.

**Comment by lebotlan** [comment]
This was it, indeed : I just deleted .opam/plugins/opam-publish and now 'opam-publish prepare' works as expected.

I get a problem with submit, then... (I open a new issue).

**Comment by lebotlan** [comment]
No new issue needed : unexpectedly, it worked after reinstalling opam-publish 0.3.5 and visiting a few github pages (but not configuring anything).

I had the following error 
...
server: GitHub.com
status: 400 Bad Request
...
Body:
{"message":"Problems parsing JSON","documentation_url":"https://developer.github.com/v3/oauth_authorizations/#create-a-new-authorization"}

which is fixed now... (I don't know how).
