### ISSUE TITLE
opam-publish fails for GitHub complaining about JSON formats

### ISSUE THREAD

**Issue by pirapira** [ocaml/opam-publish#56]
With `COHTTP_DEBUG` I saw
```
$ COHTTP_DEBUG=1 opam-publish submit bamboo.0.0.01
<...snip...>
>>> POST /authorizations HTTP/1.1
>>> accept: application/vnd.github.v3+json
authorization: Basic cGlyYXBpcmE6Y3Awb2RrSzY=
content-length: 62
host: api.github.com
user-agent: ocaml-github ocaml-cohttp/0.21.1
x-github-otp: 222877
>>> {"scopes":[<"repo">],"note":"opam-publish access token (sri)"}
HTTP Error 400 Bad Request
Headers:
<snip>
content-length: 138
<snip>

Body:
{"message":"Problems parsing JSON","documentation_url":"https://developer.github.com/v3/oauth_authorizations/#create-a-new-authorization"}
```

This happens on `opam-publish 0.3.5`, `atd 1.12.0`, `github 3.0.0` and `github-unix 3.0.0` with OCaml 4.04.1.

To me `[<"repo">]` looks not familiar as JSON.

**Comment by pirapira** [comment]
This might be caused by some issue in `github` or `atd`.

When I checkout [ocaml-github](https://github.com/mirage/ocaml-github.git), and run `make`, I find those extra `<` and `>` in ` _build/default/lib/github_j.ml`:
```
let write_scope = (
  fun ob sum ->
    match sum with
      
      | `Repo -> Bi_outbuf.add_string ob "<\"repo\">"
```

I can spend some more time on Tuesday (2017-08-01).

**Comment by dsheets** [comment]
Thanks for the report! I'm preparing a patch for ocaml-github now. In the mean-time, you may be able to downgrade to a previous version of ocaml-github (< 3.0.0).

**Comment by mmottl** [comment]
Thanks, I've just run into the problem myself and can confirm that downgrading helps.

**Comment by dsheets** [comment]
Should be fixed by ocaml/opam-repository#9967.

**Comment by pirapira** [comment]
Yes, downgrading `ocaml-github` to 2.3.0 worked.

In my culture, this kind of issue stays open until it's fixed on `master` so I keep this open, but practically I'm satisfied.  Thank you.

**Comment by dsheets** [comment]
mirage/ocaml-github#204 fixed the upstream bug. ocaml/opam-repository#9967 and ocaml/opam-repository#9992 deployed the fix. ocaml/opam-repository#9995 was submitted using the bugfix. mirage/ocaml-conduit#233 is still present, though, so you may have to specify `CONDUIT_TLS=native` to avoid a `Fatal error: Ssl not available`.

Thanks, again, for your report!
