### ISSUE TITLE
inconsistent with opam lint 

### ISSUE THREAD

**Issue by fxfactorial** [ocaml/opam-publish#59]
Apparently opam publish is more strict than opam lint

```
/R/conf-brotli ❯❯❯ opam publish prepare https://github.com/fxfactorial/conf-brotli/archive/v0.0.1.tar.gz
[v0.0.1.tar.gz] https://github.com/fxfactorial/conf-brotli/archive/v0.0.1.tar.gz downloaded
[ERROR] Package version unspecified
~/R/conf-brotli ❯❯❯ opam lint opam                                                                                  ⏎
~/Repos/conf-brotli/opam: Passed.
```

**Comment by AltGr** [comment]
That may happen, if `opam-publish` was linked against a newer version of opam, implementing more checks.

However, here, it is not a lint error: `opam-publish` could simply not infer the version of the package you want to publish, which it needs to know. Either add a `version:` field to your opam file, or use `opam publish prepare PACKAGE.VERSION URL`.
