### ISSUE TITLE
Some feedback about (possibly?) easy improvements 

### ISSUE THREAD

**Issue by jordwalke** [ocaml/opam-publish#60]
While [publishing a package](https://github.com/ocaml/opam-repository/pull/10869#issuecomment-347429216), I encountered some friction with using `opam-publish`. If we are to encourage using `opam-publish` as the primary means of publishing to opam, `opam-publish` maintainers might be interested in this feedback:

> 1.The release directory doesn't seem to be updated when trying a second time: I fixed my 3.0.3 release hosted on github, and reran the opam-publish prepare && opam-publish submit reason.3.0.3 commands, but since I had a left over reason.3.0.3/ directory with the opam/desc/url file, it didn't update it to see my new changes that I made since trying again. That seems like an easy thing to fix, but I'm curious if anyone else ran into it.
> 2. opam-publish required that I brew install gmp. That's not ideal, but not sure if there's another way. 

Some more feedback:
1. It feels weird to enter your github password/2FA into a CLI tool that is not baked into opam itself.
2. Also, it was really difficult to get `opam-publish` installed on my machine `gmp` aside. It ended up being my fault because I had another global `ocaml` compiler installed on my machine (not installed through opam) which was screwing up builds in my switch (partially my fault, partially opam's for not isolating the environment sufficiently).
3. I had some package conflicts with `opam-publish`'s dependencies that required that I downgrade some packages, and that downgrade itself failed as well. I ended up having to create a brand new switch. This problems stems from the fact that `opam-publish` is an opam package itself that is installed into the global opam switch (by default - that's what the user will end up doing 99% of the time).

These three points of friction that I experienced has me wondering if a tool like`opam-publish` should be baked into opam itself. It would eliminate many of the issues I had with `opam-publish`. cc @avsm

**Comment by AltGr** [comment]
opam-publish is being redesigned, so your feedback is particularly useful now. I'll try to take all this into account now :)

**Comment by AltGr** [comment]
Getting back to you now that the redesign is complete (it's designed for repositories in opam 2 format though, so not to be used just yet).

1. The overall workflow was too complex and convoluted. The new version doesn't query opam (neither repositories nor pins), and just gets the `opam` files from the source. Also the `prepare` and `publish` steps have been merged in just a single command.
2. The tool now offers to generate a token for you (through login/pass/2fa), or let you provide one.
3. Installation issues: apparently it's `ocaml-github` that requires `gmp`, through `tls`, `nocrypto` and `zarith`. Not sure if there are plans to change this in the above packages.
3. The above dependencies make it unrealistic to bake into opam. Also, I'm not comfortable with encoding Github specific behaviour in opam itself, even if we were to rewrite all API calls to go through `curl` manually. Last on this, I hope to release opam more frequently in the future, but it's been invaluable to be able to release `opam-publish` separately, and more frequently, until now. It didn't even exist when 1.2.2 was released, IIRC.
4. opam 2.0.0~beta5 enables you to use plugins across switches, which would help a little with the installation issues (although I agree it's not a complete solution)
5. The new version will be maintained on top of more recent (and hopefully, more stable) libraries, which should make it less of a pain to install.
