### ISSUE TITLE
opam-publish mangles depext.

### ISSUE THREAD

**Issue by toolslive** [ocaml/opam-publish#62]
```
depexts:[
  [[ "ubuntu"] ["librdmacm-dev" "libibverbs-dev"] ]
]
```
becomes
```
depexts: [
  ["ubuntu"]
  ["libibverbs-dev" "librdmacm-dev"]
]
```
when it's pulled through `opam-publish` prepare

**Comment by AltGr** [comment]
opam 1.2 didn't have the "syntax-preserving" reprinter. This should be solved in the 2.0 version (now available, but only for submissions to the 2.0.0 branch of opam-repository).
Thanks for reporting!
