### ISSUE TITLE
validation might be too strict

### ISSUE THREAD

**Issue by c-cube** [ocaml/opam-publish#64]
I can't publish some of my packages with opam-publish 2.0.0~beta because it fails when validating the `opam` file (which has a version field "1.2").

My packages have been accepted on opam-repo despite this and I would like not to have to update the opam files to continue using opam publish. It would be nice to at least have a flag `--no-validate` or similar…

**Comment by rjbou** [comment]
opam-publish 2.0.0~beta is intended for publications in the 2.0 format (cf. [CHANGES](https://github.com/ocaml/opam-publish/blob/2.0/CHANGES#L2)). You can use opam-publish.0.3.5 for 1.2 opam format.

**Comment by c-cube** [comment]
If other non-fatal warnings don't prevent publication of a package, then I can close that, thank you.

**Comment by AltGr** [comment]
Otherwise, flag `--force` may be what you were looking for.
