### ISSUE TITLE
opam-publish ignores descr files

### ISSUE THREAD

**Issue by mseri** [ocaml/opam-publish#69]
Some PRs submitted via opam-publish are missing the description in the opam file, as if opam-publish ignored the descr file. As an example see https://github.com/ocaml/opam-repository/pull/12714 but I have noticed that my cohttp PR has the same issue and it's not alone

**Comment by AltGr** [comment]
Ah, indeed, the new format includes all in the `opam` file, but the automatic conversion from 1.2 should take them into account. Thanks for reporting!
