### ISSUE TITLE
opam-publish submit no longer works (2.0.0)

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/opam-publish#73]
It seems to try to publish a package named `submit` ? Did the workflow complety change ? Where is the documentation ?

**Comment by AltGr** [comment]
Yes, the workflow completely changed, just `opam-publish` should now be enough in the majority of cases. See the [2.0 README](https://github.com/ocaml/opam-publish/tree/2.0) , and the manpages.

**Comment by dbuenzli** [comment]
Frankly you could at least announce when you make these changes and not hide them in a branch.
