### ISSUE TITLE
Cannot publish package

### ISSUE THREAD

**Issue by chrisnevers** [ocaml/opam-publish#81]
I'm trying to publish my first simple OPAM package. But I'm running to this error that I don't know how to deal with? I am in my git directory while running this command and a .git folder exists.

```
↑↑ ◎ Chris:bitlib Chris$ opam publish https://github.com/chrisnevers/bitlib/archive/v0.0.1.zip .

The following will be published:
  - bitlib version 0.1.1 with opam file at
    /Users/Chris/Documents/Projects/bitlib/bitlib.opam
    archive at https://github.com/chrisnevers/bitlib/archive/v0.0.1.zip


Continue ? You will be shown the patch before submitting. [Y/n] y
Fetching the package repository, this may take a while...
[ERROR] Uncaught exception: "/usr/local/bin/git fetch --multiple origin user"
        exited with code 128 "fatal: not a git repository (or any of the parent
        directories): .git"
```

**Comment by thosakwe** [comment]
Getting the same error.

**Comment by rjbou** [comment]
Thanks for the report!

Can you check that the directory  `~/.opam/plugins/opam-publish/repos/ocaml%opam-repository` exists and doesn't contain a `.git` directory.

@chrisnevers repository is replicated in the opam root, not the current folder. It seems that the repository has not been well cloned (missing git`).

**Comment by chrisnevers** [comment]
I got it working! 
1. I added an ssh key to my github account, 
2. Deleted `~/.opam/plugins/opam-publish/repos/` directory.
3. Re-ran `opam-publish https://github.com/chrisnevers/bitlib/archive/v0.0.1.tar.gz`
