### ISSUE TITLE
opam-publish prepare does not seem to find the package

### ISSUE THREAD

**Issue by jserot** [ocaml/opam-publish#87]
When trying to publish a package, following the steps described in the README, i get this error: 

```$ opam-publish prepare
[ERROR] Not enough information to publish. Here is what I could gather:
  - prepare version 0.6 with opam file NONE FOUND
```
It seems that  `opam-publish` interprets `prepare` as the name of the package.
The command is run from git repo, with a `.opam` file for the package generated by `dune 1.11`. `opam-publish` version is 2.0.0.

A similar problem arises when trying the second form:

```
$ opam-publish prepare lascar.0.6 "https://github.com/jserot/lascar/archive/0.6.tar.gz"
opam-publish: DIR|URL|OPAM|PROJECT|NAME... arguments: Invalid argument
Usage: opam-publish [OPTION]... [DIR|URL|OPAM|PROJECT|NAME]...
```

The `prepare` sub-command does not seem to be recognized.

Am i missing / misinterpreting sth ? 

ps : the information given in the README of the github repo is not consistent with that given in `https://opam.ocaml.org/doc/Packaging.html`..

**Comment by rjbou** [comment]
At that time, the default readme was for 0.3.5, not for 2.0.0, that's why opam-publish 2.0 didn't understand the `prepare` command. 2.0 branch was merged on master since.
Thanks!
