### ISSUE TITLE
Uncaught exception when publishing

### ISSUE THREAD

**Issue by jrochel** [ocaml/opam-publish#92]
This happens for every package, not just for eliom:

```
master:~/eliom> opam publish

The following will be published:
  - eliom version 6.9.3 with opam file at /home/jan/eliom/opam
    archive at https://github.com/ocsigen/eliom/archive/6.9.3.tar.gz


Continue ? You will be shown the patch before submitting. [Y/n] y
Fetching the package repository, this may take a while...
[ERROR] Uncaught exception: "/usr/bin/git fetch --multiple origin user" exited with code
        1 "error: Impossible de récupérer user"
```

**Comment by XVilka** [comment]
Should be fixed with the new release: https://github.com/ocaml/opam-publish/releases/tag/2.0.2
Please pin and retry.

**Comment by jrochel** [comment]
@XVilka Thanks. It does seem like _something_ has been fixed, however I am still getting an exception:
```
Fetching the package repository, this may take a while...
[ERROR] Uncaught exception: "/usr/bin/git fetch --multiple origin user" exited with code
        1 "error: impossible de dépaqueter l'entête
        dda40c55b53850c7b6a1e89b74808596d19ba922"
```

That translates to "impossible to unpack header(s)" btw.

**Comment by rjbou** [comment]
You seem to have an inconsistency in the internal clone of opam repository at `<opam root>/plugins/opam-publish/repos/ocaml%opam-repository`.Can you check that this git clone, does it fetch for ex.
To unlock quickly, you can remove  this directory, `opam-publish` will recreate it.
And we should add a fallback, in case of problem, delete it and retry maybe... it's not ideal, but at least don't block user. Or a `git reset --hard`, more soft.

**Comment by jrochel** [comment]
That resolved it. Thanks a lot!
