### ISSUE TITLE
[ERROR] Uncaught exception: "The file or folder https://github.com/ocaml/opam-repository/pull/XXXX does not exist.""

### ISSUE THREAD

**Issue by XVilka** [ocaml/opam-publish#93]
While running `opam publish` 2.0.2 version on my new [Yara package](https://opam.ocaml.org/packages/yara) release - see the PR at https://github.com/ocaml/opam-repository/pull/15501

Note, that PR was successfully created, the exception happens after, it seems:
```
Cloning the package repository, this may take a while...
+ /usr/bin/git "clone" "git@github.com:ocaml/opam-repository.git" "/home/akochkov/.opam/plugins/opam-publish/repos/ocaml%opam-repository"
- 正克隆到 '/home/akochkov/.opam/plugins/opam-publish/repos/ocaml%opam-repository'...
正在更新文件: 100% (14731/14731), 完成.
Fetching the package repository, this may take a while...

File a pull-request for this patch ? [Y/n] Y
Pull-requested: https://github.com/ocaml/opam-repository/pull/15501
[ERROR] Uncaught exception: "/usr/bin/xdg-open https://github.com/ocaml/opam-repository/pull/15501" exited with code 4 "kf5.kio.widgets: KRun(0x55893d603d60) ERROR (stat): 111   "The file or folder
        https://github.com/ocaml/opam-repository/pull/15501 does not exist.""
```

**Comment by rjbou** [comment]
After opening the PR, opam-publish opens the resulted webpage. Can you check that the result of command `/usr/bin/xdg-open https://github.com/ocaml/opam-repository/pull/15501` ?
Even if it fails, it should be an hard error as here.

**Comment by XVilka** [comment]
It works now, after the machine reboot. Probably some system problem or updates problem.
